#ifndef OBSERVER_INCLUDE_DISPLAY_ELEMENT_INTERFACE_HPP
#define OBSERVER_INCLUDE_DISPLAY_ELEMENT_INTERFACE_HPP

class DisplayElement{
public:
    virtual void display() = 0;
};

#endif // OBSERVER_INCLUDE_DISPLAY_ELEMENT_INTERFACE_HPP